rgname = "terraform-automated-rg"
location = "Central India"
vnet_name = "terraform-automated-vnet"
subnet_name = "terraform-automated-vnet"
mynic_name = "terraform-automated-nic"
vm_name = "terraform-automated-vm"
